# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-11 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("marketing_blocks", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="marketingblock", options={"ordering": ["-active", "-modified"]}
        )
    ]
