# Generated by Django 2.2.4 on 2019-11-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_blocks', '0002_auto_20190723_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingblock',
            old_name='content',
            new_name='content_mailchimp',
        ),
    ]
