# Generated by Django 2.2.15 on 2020-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing_blocks", "0007_auto_20200819_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingblock",
            name="label",
            field=models.CharField(default="", max_length=100, null=True, blank=True),
        ),
    ]
