# Generated by Django 2.2.24 on 2021-09-21 10:56

from django.db import migrations


def from_content_sendgrid_to_content(apps, schema_editor):
    MarketingBlock = apps.get_model("marketing_blocks", "MarketingBlock")
    for block in MarketingBlock.objects.all():
        block.content = block.content_sendgrid
        block.save()


class Migration(migrations.Migration):

    dependencies = [
        ("marketing_blocks", "0012_auto_20210921_1255"),
    ]

    operations = [migrations.RunPython(from_content_sendgrid_to_content)]
