# Generated by Django 2.2.24 on 2021-09-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing_blocks", "0013_auto_20210921_1256"),
    ]

    operations = [
        migrations.RemoveField(model_name="marketingblock", name="content_sendgrid",),
    ]
